export const USER_FETCHED = 'USER_FETCHED';
export const USER_UPDATED = 'USER_UPDATED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_FAILURE = 'COMPANIES_FAILURE';


export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

export const TOPICS_FETCH_SUCCESS = 'TOPICS_FETCH_SUCCESS';
export const TOPICS_FETCH_FAILURE = 'TOPICS_FETCH_FAILURE';


export const ADD_TOPICS_SUCCESS = 'ADD_TOPICS_SUCCESS';
export const ADD_TOPICS_FAILURE = 'ADD_TOPICS_FAILURE';

export const VOTED_SUCCESS = 'VOTED_SUCCESS';
export const VOTED_FAILURE = 'VOTED_FAILURE';

export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAILURE = 'DELETE_TOPIC_FAILURE';

export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const PROJECT_VOTED_SUCCESS = 'PROJECT_VOTED_SUCCESS';
export const PROJECT_VOTED_FAILURE = 'PROJECT_VOTED_FAILURE';

export const TEAMS_SUCCESS = 'TEAMS_SUCCESS';
export const TEAMS_FAILURE = 'TEAMS_FAILURE';
